package com.cloudbalancer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class fleet implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public fleet() {
    }




}